### PR TITLE
turning gun-sales repo into a package gunsales

### PR DESCRIPTION
**Pull request by eddelbuettel**
I reorganised the code a little, and took advantage of some concurrent work which @christophsax (the author of seasonal) and I are doing in order to support _fully automatic installation of this package, seasonal and the required x13 binary_.   This now works.  Running this R code

``` r
if (!requireNamespace("drat", quietly=TRUE)) install.packages("drat")     # helper
drat::addRepo("ghrr")                                      # add a repo containing these
install.packages("gunsales", type="source")                # installs all, plus depends
```

is all it takes. If an when we have updated versions of seasonal and the x13binary package it now depends upon CRAN, this will simplify to

``` r
install.packages("gunsales")
```

After that:

``` r
library(gunsales)    # load package
analysis()           # run analysis -- ie what was in main.R
```

will create the dozen or so graphs.  If you run this inside RStudio you can already cycle through the plots.

I want to make at least one more change to export the data sets from `analysis()` back to the caller. 

(NB: name change because R does not like '-' in package names.)

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Hold on. Just found another bug.  Will report back.

**Comment by eddelbuettel** [comment]
This now works for me 'as advertised':  
- dependencies declared, and `x13` installed automatically
- code reorganised into package with data and functions, documented
- package passes `R CMD check` cleanly

but it might be best if I do one more test, and we have a bit more cleanup to do on the x13binary and seasonal side.

**Comment by gka** [comment]
ok, will start to pull it in

**Comment by eddelbuettel** [comment]
Ace.

I see that GH now calls this a conflict. I can try to sort things out on my end. @christophsax and I are making good progress on the x13binary and seasonal side, and I started writing up a brief vignette so that people can work with this in detail.  We'll get there in the next few days.

And congrats on an updated page 1!

**Comment by gka** [comment]
No that’s because of me updating the data and fixing a bug in the script. looking into the merge now, so don’t worry about it.

-- 
Gregor Aisch | Graphics Editor | The New York Times | 212-556-1910

On January 5, 2016 at 5:08:55 PM, Dirk Eddelbuettel (notifications@github.com) wrote:

Ace.

I see that GH now calls this a conflict. I can try to sort things out on my end. @christophsax and I are making good progress on the x13binary and seasonal side, and I started writing up a brief vignette so that people can work with this in detail. We'll get there in the next few days.

And congrats on an updated page 1!

**Comment by eddelbuettel** [comment]
I just dealt with that -- carrying the few lines in `main.R` over and updating the data.

The stored (now binary data) does not yet reflect your new csv.  Give me a moment (and this may be until tomorrow...)

**Comment by gka** [comment]
think I just did that by running `.rawDataToSavedData()` :)

**Comment by gka** [comment]
just tried installing the package via `devtools::install_github()` but it gave me this error:

``` R
> devtools::install_github('NYTimes/gun-sales')
Downloading GitHub repo NYTimes/gun-sales@master
Installing gunsales
Skipping 1 packages not available: x13binary
Installing 5 packages: curl, R6, Rcpp, readr, stringi
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/xg/l9221qkx441d6c_4c9_dl6_dnyd488/T/RtmptaDexS/devtools16e08f2fb949/NYTimes-gun-sales-bfeecee'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library' --install-tests 

ERROR: dependency ‘x13binary’ is not available for package ‘gunsales’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/gunsales’
Error: Command failed (1)
```

That's because `x13binary` is not yet a package?

**Comment by eddelbuettel** [comment]
Is there a number I can call you at?

**Comment by gka** [comment]
_removed_

**Pull request merged**
